from enum import Enum


class PipelineStage(str, Enum):
    INIT = "INIT"
    INPUTS_LOADED = "INPUTS_LOADED"
    REPORTS_NORMALISED = "REPORTS_NORMALISED"
    REPORTS_INTERPRETED = "REPORTS_INTERPRETED"
    PATTERNS_GROUPED = "PATTERNS_GROUPED"
    PRIORITIES_COMPUTED = "PRIORITIES_COMPUTED"
    CASES_SELECTED = "CASES_SELECTED"
    ROUTING_COMPLETE = "ROUTING_COMPLETE"
    EXPLANATIONS_GENERATED = "EXPLANATIONS_GENERATED"
    VALIDATION_COMPLETE = "VALIDATION_COMPLETE"
    RESULTS_FINALISED = "RESULTS_FINALISED"